# Additional DB Configurations
# ===
spring.jpa.hibernate.ddl-auto=update
logging.level.root=ERROR

# Authentication Configuration (Clerk)
# ===
auth.validator.type=clerk

# Prod
clerk.jwks.url=${CLERK_JWKS_URL}

# Local
#clerk.jwks.url=${CLERK_JWKS_URL}
